# Use root/example as user/password credentials
version: '3.1'

services:
  backend-db:
    image: kartoza/postgis:15-3.3
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5431:80'
      