# Use root/example as user/password credentials
version: '3.1'

services:
  backend-db:
    image: kartoza/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5432:5432