version: '3.1'

services:
  postgres:
    container_name: datatlas-db
    image: docker.io/kartoza/postgis
    restart: unless-stopped
    privileged: true
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASS: ${POSTGRES_PASSWORD:-docker}
      ALLOW_IP_RANGE: ${ALLOW_IP_RANGE:-0.0.0.0/0}
      RUN_AS_ROOT: true
    ports:
      - '5432:${POSTGRES_PORT}'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5431:80'
