version: '3.1'

services:
  postgres:
    container_name: datatlas-db
    image: kartoza/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASS: ${POSTGRES_PASSWORD:-docker}
      ALLOW_IP_RANGE: ${ALLOW_IP_RANGE:-0.0.0.0/0}
    ports:
      - '5432:${POSTGRES_PORT}'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5431:80'
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgpass

  backend:
      container_name: dev-datatlas-backend
      build:
        dockerfile: dev.Dockerfile
        context: .
      command: backend
      depends_on:
        - postgres
      env_file:
        - .env
      #volumes:
        #- ./apps/backend:/datatlas/apps/backend
        #- ./node_modules:/datatlas/node_modules
      ports:
        - 3333:3333

  frontend:
    container_name: datatlas-frontend
    build:
      dockerfile: dev.Dockerfile
      context: .
    command: frontend
    env_file:
      - .env
    #volumes:
      #- ./apps/frontend:/datatlas/apps/frontend
      #- ./node_modules:/datatlas/node_modules
    mem_limit: 2048m
    ports:
      - 3000:3000