version: '3.1'

services:
  postgres:
    container_name: datatlas-db
    image: kartoza/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASS: ${POSTGRES_PASSWORD:-docker}
    ports:
      - '5432:${POSTGRES_PORT}'

  backend:
    container_name: datatlas-backend
    build:
      dockerfile: Dockerfile
      context: .
      target: backend
      args:
        - COPY_PATH=backend
    restart: always
    ports:
      - '3333:3333'

  frontend:
    container_name: datatlas-frontend
    build:
      dockerfile: Dockerfile
      context: .
      target: frontend
      args:
        - COPY_PATH=frontend
    restart: always
    ports:
      - 3000:80
