# Use root/example as user/password credentials
version: '3.1'

services:
  backend-db:
    container_name: datatlas-db
    image: kartoza/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
    ports:
      - '5432'

  backend:
    container_name: datatlas-backend
    build:
      dockerfile: Dockerfile
      context: .
      target: backend
      args:
        - TARGET=backend
    restart: always
    ports:
      - 3333:3333

  frontend:
    container_name: datatlas-frontend
    build:
      dockerfile: Dockerfile
      context: .
      target: frontend
      args:
        - TARGET=frontend
    restart: always
    ports:
      - 3000:80
