apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  type: {{ .Values.postgisPgadmin.postgisService.type }}
  ports:
    - name: postgis
      port: {{ .Values.postgisPgadmin.postgisService.port }}
      targetPort: {{ .Values.postgisPgadmin.postgisService.targetPort }}
      protocol: TCP
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-{{ .Release.Namespace }}-postgis-pgadmin
  strategy:
    type: {{ .Values.frontend.strategy.type | default "Recreate" }}