name: Lint, test & build
on:
  push:
    branches:
      - dev
      - main
  pull_request:

env:
  BASE_BRANCH: dev
  POSTGRES_PASSWORD: postgres
  ADMIN_EMAIL: admin@example.org
  ADMIN_PASSWORD: admin
  DUMMY_EDITOR_EMAIL: editor@example.org
  DUMMY_EDITOR_PASSWORD: editor

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: $BASE_BRANCH
      - run: npm ci --legacy-peer-deps
      - run: npx nx format:check --base=$BASE_BRANCH
      - run: npx nx affected --target=lint --parallel=3 --base=origin/$BASE_BRANCH
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage --base=origin/$BASE_BRANCH
      - run: |
          npx nx serve backend &
          npx wait-on http://localhost:3333/api
      - run: npx nx e2e backend-e2e
      - run: npx nx affected --target=build --parallel=3 --base=origin/$BASE_BRANCH
