name: Lint, test & build
on:
  push:
    branches:
      - dev
      - main
  pull_request:

env:
  BASE_BRANCH: dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: $BASE_BRANCH
      - run: npm install --legacy-peer-deps
      - run: npx nx format:check --base=$BASE_BRANCH
      - run: npx nx affected --target=lint --parallel=3 --base=origin/$BASE_BRANCH
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage --base=origin/$BASE_BRANCH
      - run: npx nx affected --target=build --parallel=3 --base=origin/$BASE_BRANCH
